const teams = {
  "A": { name: "Team A 立春 AI", location: "San Francisco / Berkeley, CA", region: "北湾 North Bay", members: [
    { en: "Ivy Lin", cn: "林小蝶", loc: "San Francisco, CA", company: "TikTok - PD", note: "计算机背景，UMich HCI 19', 曾就职于Deloitte, C3 AI, enterprise ai 工具，vibe coding，creative tools，developer tools。探讨AI x Design工作流结合，vibe coding, creative platform and tools, drive impact as designers" },
    { en: "Olivia Ouyang", cn: "", loc: "San Francisco, CA", company: "Meta - PD", note: "Currently working in Meta. Previously at Finix Payments, Flexport and Step mobile banking app. Masters in HCI, undergrad in EE. 想认识更多设计师朋友，做design system相关的platform work，想了解如何向上管理以及stakeholder management" },
    { en: "Tiantian Xu", cn: "", loc: "San Francisco, CA", company: "Snowflake - PD", note: "HCI, Product Designer. AI native workflow 对设计师的影响" },
    { en: "Xiyu Zhang", cn: "张曦予", loc: "San Francisco, CA", company: "Xperi - UX", note: "本科Information Systems，研究生Web Design & New Media。主攻Automotive HMI方向，车载娱乐多媒体软件设计。近期想要跳槽，AI环境下产品设计的变化与不变" },
    { en: "Xuan Shen", cn: "沈萱", loc: "San Francisco, CA", company: "Extend - PD", note: "Extend产品帮助商家处理各类售后服务。之前在UC Berkeley&同济学习景观建筑学。提升design craft! 26年也要开始做作品集找新的工作机会了" },
    { en: "Lucy Chen", cn: "陈小树", loc: "Berkeley, CA", company: "Handshake AI - Head of Learning & Training", note: "一直做教育，目前在Handshake AI带团队做学习体验设计。跨组合作的注意事项，工作中AI赋能的机会，如何做好向上沟通管理和影响xfn team" },
  ]},
  "B": { name: "Team B 雨水 Growth", location: "San Francisco, CA", region: "北湾 North Bay", members: [
    { en: "Yidi", cn: "洪依迪", loc: "San Francisco, CA", company: "LinkedIn - UED", note: "背景心理学，之前在湾区startup，现在在LinkedIn做UX designer。想更多了解career path的发展, 学习design leadership和communication" },
    { en: "Ashley Sun", cn: "", loc: "San Francisco, CA", company: "Zelle - Lead UX Designer", note: "现在Zelle做Lead UX Designer。清华建筑本科，哈佛设计学院master。此前有11年景观建筑和城市设计经验。职业发展经验交流" },
    { en: "Hailey Liu", cn: "刘梦洁", loc: "San Francisco, CA", company: "Verkada - PD", note: "Fashion Marketing本科, AAU Web Design研究生。在Verkada做workplace安全相关设计。争取team资源，各种product development framework，设计项目管理" },
    { en: "Judy Ziyu Zhu", cn: "小昱", loc: "San Francisco, CA", company: "ex-Meta (gap year)", note: "来Meta之前在Yahoo做过4年PD。本科中国传媒大学动画，研究生CMU ETC。和大家交流设计师的职业规划和成长" },
    { en: "Yan Yan", cn: "晏岩", loc: "San Francisco, CA", company: "Instagram - PD", note: "Stanford University 产品设计学士学位。此前就职于startups、Apple与Microsoft。对如何打造有归属感的设计社区特别感兴趣，探讨成长型领导力" },
  ]},
  "C": { name: "Team C 惊蛰 Culture", location: "San Francisco / Burlingame, CA", region: "北湾 North Bay", members: [
    { en: "Yiran Ma", cn: "马一然", loc: "San Francisco, CA", company: "Verily - PD", note: "本科清华工业工程，Georgia Tech MSHCI。现在在Verily负责health AI产品。设计岗位的进阶经验，如何在商业主导的团队中为产品的用户体验争取更多关注和资源" },
    { en: "Yuhan Xie", cn: "", loc: "San Francisco, CA", company: "LinkedIn - PD", note: "PD at LinkedIn, 主要做Consumer Analytics产品。UCB Data Science本科, UW HCDE研究生。想了解不同行业的产品趋势，探索AI对产品设计和职业规划的影响" },
    { en: "Yuyin Sun", cn: "", loc: "San Francisco, CA", company: "Reacher - PD", note: "TikTok Affiliate AI Startup。了解现在Design发展趋势，向有经验的人学习" },
    { en: "Beatrice", cn: "", loc: "San Francisco, CA", company: "OF - PD", note: "B2B Enterprise。希望深耕fintech产品" },
    { en: "Yun Tang", cn: "", loc: "San Francisco, CA", company: "Medidata - PD", note: "CMU and Healthtech。各种设计方面的实操经验和技巧" },
    { en: "Becca Guo", cn: "郭梦佳", loc: "Burlingame, CA", company: "Bellota - PD", note: "UMN CS / Cornell IS，曾在Glu，网易游戏，Jam City做UX/UI，现为Gaming Startup的Principal PD。Vibe Coding/Designing, 了解Tech行业对UX/PD的考察维度" },
  ]},
  "D": { name: "Team D 春分 Trends", location: "San Mateo, CA", region: "半岛 Peninsula", members: [
    { en: "Yiqi Zhao", cn: "", loc: "San Mateo, CA", company: "Meta - PD", note: "AI, Spatial Intelligence, World Model, ex-Unity, ex-Bungie. Harvard/MIT - HCI, Brain Computer Interface, ARVR. 研究AI自动赚钱，辞职退休" },
    { en: "Aoni Wang", cn: "王奥妮", loc: "San Mateo, CA", company: "Instagram - PD", note: "目前在Instagram做product design。之前在Chime和MailTime工作，设计经验主要是从0到1的to C移动端产品设计。如何用AI赋能，和领导层的合作与展示" },
    { en: "Yingzi Zhang", cn: "张瑛子", loc: "San Mateo, CA", company: "Moxo - UXD", note: "AAU web design毕业。Career Path (Mid to Senior)，想讨论职业发展的问题，组团打怪升级" },
    { en: "Ruo Cheng", cn: "", loc: "San Mateo, CA", company: "AWS - UX", note: "做过healthcare research/design, 目前是AWS UX designer。结交设计师朋友，了解行业趋势" },
    { en: "Grace Guo", cn: "郭艾琛", loc: "San Mateo, CA", company: "Workday - PD", note: "UC Berkeley本科 & Pratt研究生。探讨工作中的问题，了解AI在设计过程中的应用和AI design principles" },
    { en: "Beverly", cn: "", loc: "San Mateo, CA", company: "Arctera", note: "UMich HCI毕业，现在在做data protection软件。聊设计 交朋友 副业等" },
  ]},
  "E": { name: "Team E 谷雨 Growth", location: "San Mateo, CA", region: "半岛 Peninsula", members: [
    { en: "Yiwei Xu", cn: "", loc: "San Mateo, CA", company: "Airwallex - PD", note: "现在在Airwallex做AI Native product, 之前在C3.ai当Design Manager。UMSI毕业。职业发展，了解行业动向(B2B/AI)" },
    { en: "Qian Wan", cn: "", loc: "San Mateo, CA", company: "Handshake - PD", note: "在Handshake做Product Designer。之前从事景观设计工作。想讨论产品设计以及求职相关的话题，做初创公司的经验分享" },
    { en: "Hanyu Gong", cn: "", loc: "San Mateo, CA", company: "Asana - PD", note: "之前在Google, SimpliSafe工作。Georgia Tech - HCI, 浙大广告+工设。交流未来design in tech会怎么变化" },
    { en: "Lebin Qi", cn: "", loc: "San Mateo, CA", company: "Cornerstone OnDemand - PD", note: "本科Supply Chain Management专业, AAU Web Design Master。认识新的设计师朋友，交流2B SaaS产品和Data Viz产品的设计经验" },
    { en: "Siyu Lei", cn: "", loc: "San Mateo, CA", company: "Zaiye - PD", note: "本科浙大产品设计，MA Royal College of Art。之前在NIO做HMI Experience Manager。刚来美国想多认识不同领域的设计师" },
    { en: "Tianmi Fang", cn: "方小米", loc: "San Mateo, CA", company: "Rubrik - UXR", note: "B2B/B2C UX Research; B2C UX Design; Psychology+Industrial Design+HCI。UX Design/Research with AI and for AI" },
  ]},
  "Z": { name: "Team Z 立夏 Community", location: "San Mateo / Belmont, CA", region: "半岛 Peninsula", members: [
    { en: "YiWu", cn: "51", loc: "San Mateo, CA", company: "Apple (agency) - PD", note: "Columbia University Architecture & Urban Design Master。从UD转行到UX，embed在Apple的design agency工作。希望交流工作心得，组织或加入学习小组" },
    { en: "Manni Li", cn: "李曼妮", loc: "Belmont, CA", company: "Meta - PD", note: "研究生UI/UX专业, 之前在Meta和Global Payments, 专注于B2B领域和enterprise产品设计。希望探讨Career growth和练习面试" },
    { en: "Vicky Gao", cn: "", loc: "San Mateo, CA", company: "DoorDash - PD", note: "在DoorDash做product designer。希望一起交流设计以及产品相关的信息" },
    { en: "Roy", cn: "罗伊", loc: "San Mateo, CA", company: "eBay - PD", note: "建筑背景，19年开始工作。沟通合作能力" },
  ]},
  "F": { name: "Team F 小满 Growth", location: "Fremont, CA", region: "东湾 Fremont", members: [
    { en: "Emma Wang", cn: "", loc: "Fremont, CA", company: "UX (Gaming)", note: "UX Designer in Gaming, 前EA, 网易。认识设计行业小伙伴，探讨职业发展，交流tech公司面试流程和技巧" },
    { en: "Bella", cn: "", loc: "Fremont, CA", company: "PwC - UXD", note: "User Experience Designer。在创业公司里以及和不熟悉UX的环境里，如何表达和定位" },
    { en: "Yao Cheng", cn: "成瑶", loc: "Fremont, CA", company: "Facebook (Contractor) - PD", note: "在Facebook做product designer. 研究生毕业于米兰理工大学, 产品服务系统设计专业。设计师应用AI的各种心得以及职业成长" },
    { en: "Qing He", cn: "", loc: "Fremont, CA", company: "Meta - PD", note: "Master degree in Graphic Design. Meta Enterprise team, Video-creation tools for K12 at Startup. 想往Senior designer提升，想练习白板" },
  ]},
  "G": { name: "Team G 芒种 AI", location: "Mountain View, CA", region: "南湾 South Bay", members: [
    { en: "Charlene Luo", cn: "罗哲宁", loc: "Mountain View, CA", company: "Blend - PD", note: "TikTok Shop C端做Product Designer。想要学习更多mentor的能力，以及AI辅助设计的探索" },
    { en: "Chloe Du", cn: "杜佳男", loc: "Mountain View, CA", company: "LinkedIn - PD", note: "Product designer，背景是学城市规划/房地产。希望可以交流career path相关的话题" },
    { en: "Crystal Shan", cn: "单冰清", loc: "Mountain View, CA", company: "Yam - Cofounder", note: "在UMich读UX硕，本科建筑景观设计。之前在Cisco Webex做ecomm/admin portal/AI agent studio设计。现在在创业，喜欢琢磨AI应用和vibe coding/designing" },
    { en: "Youyang Hou", cn: "悠扬", loc: "Mountain View, CA", company: "Job Seeking - UXR", note: "心理学/HCI PhD背景，曾就职于Google/Lyft，多年AI, SaaS, enterprise, dev tools相关用研经验。AI and agent product strategy" },
    { en: "Shan Wang", cn: "", loc: "Mountain View, CA", company: "Google Labs - PD", note: "CMU HCI + 建筑。现在Google Labs负责NotebookLM。Long-term career growth + leadership; IC/management track exploration; product strategy" },
    { en: "Frederic Liu", cn: "", loc: "Mountain View, CA", company: "Meta - PD", note: "Currently PD at Meta Superintelligence Labs, Previously Yahoo - Google - GT HCI - SJTU ID. 设计思考和行业洞察" },
    { en: "Mika Jiang", cn: "", loc: "Mountain View, CA", company: "Slack - PD", note: "PD@Slack, GT HCI. 了解行业动态，像小伙伴们学习，AI时代创业" },
  ]},
  "H": { name: "Team H 夏至 Growth", location: "Santa Clara, CA", region: "南湾 South Bay", members: [
    { en: "Peidi Sun", cn: "", loc: "Santa Clara, CA", company: "Aviatrix - PD", note: "Network Security Senior UX Designer。提升hard & soft skills，向不同领域的设计师小伙伴学习和交流" },
    { en: "Yaxin Zheng", cn: "郑雅馨", loc: "Santa Clara, CA", company: "LinkedIn - PD", note: "本科复旦心理学，研究生IUB人机交互。目前在LinkedIn做Learning product-enterprise side的产品设计。整理碎片化的知识，思考career path" },
    { en: "Yunyu Zhou", cn: "", loc: "Santa Clara, CA", company: "DoorDash - PD", note: "IUB HCI项目毕业，目前在DoorDash工作。想学习如何和其他设计师以及PM合作交流，如何处理disagreements" },
    { en: "Weiting Gao", cn: "", loc: "Santa Clara, CA", company: "Salesforce", note: "CMU MHCI, 前Amazon。希望能跟大家多多交流平常职场小tips，以及升职/跳槽经验" },
    { en: "Mu Jiun Shie", cn: "", loc: "Santa Clara, CA", company: "Meta - PD", note: "CMU MIIPS 2020年毕业，之前在台湾有四年工作经验。Startup跟Google(contractor)工作过，2023年加入Meta。Grow leadership and ownership, increase visibility" },
  ]},
  "I": { name: "Team I 小暑 Community", location: "Santa Clara, CA", region: "南湾 South Bay", members: [
    { en: "Joyaa", cn: "", loc: "Santa Clara, CA", company: "Sp - IXD", note: "之前是UCD的平面设计然后转的UX/UI。设计师的生活和了解行业趋势" },
    { en: "Yudi", cn: "", loc: "Santa Clara, CA", company: "Zillow - PD", note: "Mainly B2B design. How does AI impact design work" },
    { en: "Chiao Cheng", cn: "", loc: "Santa Clara, CA", company: "Apple - PD (Contract)", note: "UMich MSI 2023毕业，之前在台湾有三年工作经验。求职技能/练习，如何变成senior designer，如何应对AI趋势" },
    { en: "Huaiwei Sun", cn: "", loc: "Santa Clara, CA", company: "Decagon - PD", note: "PD at Decagon, ex-Googler, GT HCI, SJTU ID. 认识更多UX朋友" },
    { en: "Yunchi Chen", cn: "", loc: "Santa Clara, CA", company: "AWS - PD", note: "曾就职深圳腾讯，to C Mobile产品。2022赴美读SJSU master, 现在AWS做AI/MLOps方向产品。AI/了解行业动态/新知" },
  ]},
  "J": { name: "Team J 大暑 AI", location: "Sunnyvale, CA", region: "南湾 South Bay", members: [
    { en: "Qiyu", cn: "", loc: "Sunnyvale, CA", company: "Apple - PD", note: "Currently Prototyper (doing vibe coding). 2 year PD & prev full-stack dev. Cornell Information Science, CMU MHCI. 作品集storytelling, use of AI in product dev" },
    { en: "Olive Cao", cn: "曹蕴仪", loc: "Sunnyvale, CA", company: "OneSignal - SPD", note: "现在一家2B startup做PD, Landscape背景转行。Vibe coding, AI提高设计师生产力的一百种方法" },
    { en: "Dora (Yan Hong)", cn: "", loc: "Sunnyvale, CA", company: "AWS - UX", note: "Parsons DT毕业 -> L'Oreal -> Startup -> Prosper Marketplace -> AWS。跳槽、职业发展，AI如何影响面试和designer未来的角色" },
    { en: "Scarlett Wu", cn: "晓涵", loc: "Sunnyvale, CA", company: "Rubrik - PD", note: "本科东南建筑，硕士CMU MIIPS。目前在Rubrik做Cyber Security相关的产品设计。希望能探讨产品思维，职场技能" },
    { en: "Ray Zhao", cn: "赵睿", loc: "Sunnyvale, CA", company: "Walmart - PD", note: "景观转UX，现在在Walmart的intl sourcing team做B2B/internal tool。认识朋友，了解行业趋势" },
    { en: "Siqi Chen", cn: "陈思琦", loc: "Sunnyvale, CA", company: "Databento - PD", note: "上交建筑本，西北EDI硕。在fintech startup从0到1做金融数据类产品，现在为新手product design manager。提高职场soft skills，广泛使用AI拓展边界" },
  ]},
  "K": { name: "Team K 立秋 Growth", location: "Sunnyvale, CA", region: "南湾 South Bay", members: [
    { en: "Erin Yang", cn: "杨怡", loc: "Sunnyvale, CA", company: "Meta - PD", note: "UPenn建筑研究生，之前在Walmart Lab，23andMe，现在在Meta设计AR眼镜。Framework strategy, Leadership skill, Mentorship" },
    { en: "Chen Zhang", cn: "张辰", loc: "Sunnyvale, CA", company: "Google - IXD", note: "Google Cloud, Instacart Ads, AWS, B2B产品设计，设计系统。RIT设计毕业。Designer career, design team culture and design process" },
    { en: "Julia", cn: "无小川", loc: "Sunnyvale, CA", company: "Google - UXD", note: "现在在谷歌做payments platform，之前在DoorDash和Wish做C端用户增长设计。曾经是室内建筑师。最近在思考如何level up" },
    { en: "Ray Xia", cn: "", loc: "Sunnyvale, CA", company: "Job Seeking - PD", note: "Visual design本科、HCI Masters@CMU。结识更多优秀的product designers, Career opportunities" },
    { en: "Wen Zhang", cn: "", loc: "Sunnyvale, CA", company: "Scribd - PD", note: "目前在Scribd做UGC相关的workspaces design。研究生在UPenn读景观。职业发展，了解行业动向" },
    { en: "Sissi", cn: "", loc: "Sunnyvale, CA", company: "Chase - PD", note: "AAU研究生毕业，加入Chase之前在几家初创公司工作过。认识志同道合的小伙伴共同成长，career path的发展和规划" },
  ]},
  "L": { name: "Team L 处暑 Community", location: "San Jose, CA", region: "南湾 South Bay", members: [
    { en: "Ningyue Shang", cn: "", loc: "San Jose, CA", company: "Tesla - UX", note: "本科建筑背景，目前在Tesla做enterprise product design。规划career path，AI冲击下设计师如何找到自己定位" },
    { en: "Angela", cn: "孙丹睿", loc: "San Jose, CA", company: "Pure Storage", note: "Master毕业于Georgia Tech的HCI，之前是EE背景。希望能了解大公司的设计规范，与startup工作的设计师互相交流" },
    { en: "Muchen", cn: "沐晨", loc: "San Jose, CA", company: "Facebook - PD", note: "HCI毕业, 2B2C都有做过。目前希望了解如何improve communication skills" },
    { en: "Willow", cn: "洪一柳", loc: "San Jose, CA", company: "Meta - PD", note: "本科建筑@Cornell，研究生Interaction design@CMU。交流职场经验，分享讨论前沿设计领域" },
    { en: "Lorry Tang", cn: "唐巧", loc: "San Jose, CA", company: "Axon - PD", note: "商科+HCI。想要讨论2B产品设计的常见问题，最优流程。law enforcement行业的针对化设计" },
  ]},
  "M": { name: "Team M 白露", location: "Saratoga / San Jose, CA", region: "南湾 South Bay", members: [
    { en: "Luna Chen", cn: "清源", loc: "Saratoga, CA", company: "Instagram - PD", note: "本科浙大工业设计系，研究生NYU ITP。作为KP Design Fellow入行tech。如何让华人设计师职场互助成长社群sustainable地发展？AI时代Lead Design Manager的职业发展" },
    { en: "Sherry Xu", cn: "徐雪明", loc: "Saratoga, CA", company: "Meta - PD", note: "UIUC MBA, 本科华盛顿大学交互设计。原先在Roblox做Product Designer，现在在Meta。专注社交UGC相关内容。学习职业知识，交流合作中的技巧和生存法则" },
    { en: "Surong Ruan", cn: "", loc: "San Jose, CA", company: "Intuitive Surgical - IxD", note: "现在Intuitive Surgical做digital service的设计，关注Healthcare & Strategic design方向。UMich HCI 2012毕业，本科Tsinghua Automation. Service design / Design initiative / Strategy / AI+Design" },
    { en: "Chloe Chen", cn: "", loc: "San Jose, CA", company: "Google - PD", note: "B2B SaaS, 2C, A2A. AI时代，如何找到设计师的定位和发展" },
    { en: "Hengyi Ren", cn: "", loc: "Sunnyvale, CA", company: "Job Seeking - UX", note: "Founding Designer of Accio at Alibaba. HCI - IUB. Career path, Job hunting, build AI-product native products" },
  ]},
  "N": { name: "Team N 秋分", location: "Los Angeles, CA", region: "Los Angeles", members: [
    { en: "Pinxuan Lin", cn: "", loc: "Los Angeles, CA", company: "MoeGo - PD", note: "Marketing and Communication Research硕士，转行成为product designer。主要在Startup。product designer面试技巧，了解最新UI/UX行业趋势" },
    { en: "Roy Ren", cn: "", loc: "Los Angeles, CA", company: "Meta - PD", note: "ACCD产品毕业，现在Meta广告组做PD。认识更多设计师，讨论设计career" },
    { en: "Yiqi Wang", cn: "凯利", loc: "Los Angeles, CA", company: "Autodesk - PD", note: "CMU MHCI 2022, 毕业后在Autodesk，现居尔湾。2026年的挑战是找新工作，找到自己在新时代的定位。vibe-coding让设计师可以hands on做很多东西" },
  ]},
  "O": { name: "Team O 寒露 AI", location: "Bellevue / Seattle, WA", region: "Great Seattle Area", members: [
    { en: "Evelyn Zhou", cn: "", loc: "Bellevue, WA", company: "Meta - PD", note: "Supply Chain, Monitor Intelligence, Ads, Design System。认识更多朋友，vibe coding，AI时代的行业发展，career development" },
    { en: "Iris Cai", cn: "", loc: "Bellevue, WA", company: "Amazon - PD", note: "本科USC，Carnegie Mellon interaction design。在Amazon设计Last Mile Delivery给small business operations相关的产品。AI时代下如何转型成UX PM" },
    { en: "Yuhan Guo", cn: "", loc: "Bellevue, WA", company: "AWS - PD", note: "UXD @ AWS 一直在做AI/ML方面B2B design。新的工作趋势" },
    { en: "Amber Weng", cn: "", loc: "Seattle, WA", company: "AWS - PD", note: "人文社科转行UX。UX designer shift to AI builder. 如何及时学习最新的AI知识，并且开始一些side project" },
    { en: "Yuna Yang", cn: "杨芸嫣", loc: "Bellevue, WA", company: "Amazon - UX", note: "商科背景，有过两年管理咨询工作经验，然后转向UX Design。现在在做亚马逊物流相关的产品。AI时代设计师应该学习的新技能和职业转型" },
    { en: "Charlene Yang", cn: "杨景华", loc: "Bellevue, WA", company: "HubSpot - PD", note: "B2B SaaS。AI对设计师的影响" },
  ]},
  "P": { name: "Team P 霜降 Growth", location: "Bellevue / Kirkland / Seattle, WA", region: "Great Seattle Area", members: [
    { en: "Haihua Zhang", cn: "", loc: "Bellevue, WA", company: "Salesforce - UX", note: "本科清华心理学，硕士UW HCDE，之前在Amazon做UX Design。如何在新公司和复杂domain里快速学习提高design leadership和strategic thinking" },
    { en: "Wuke Zhou", cn: "周五可", loc: "Kirkland, WA", company: "Okta - PD", note: "本科NAU english+photography，硕士Pratt Institute MSinIXD。做过Comcast和Google contractor，后来VMware，现在Okta platform team。Senior level的上升路径，AI趋势下的求职变化" },
    { en: "Jia Hao (Jocelyn)", cn: "", loc: "Bellevue, WA", company: "Amazon - PD", note: "数字媒体技术教育背景。Industrial experience across B2B & B2C design in multimedia, AI, e-commerce, IoT & Data Viz, and design system。行业动态，职业发展" },
    { en: "Teenie Tang", cn: "", loc: "Bellevue, WA", company: "Apple - PD", note: "主要做design system和machine learning & developer tooling。Career growth, 和大家讨论相关设计产品的话题" },
    { en: "Lumi Wei", cn: "", loc: "Seattle, WA", company: "Microsoft - UX", note: "本科浙江大学工业设计，硕士UW GIX，目前在Microsoft做AI agent相关产品。如何提升soft skills和向上管理的能力" },
    { en: "Chufan Huang", cn: "", loc: "Bellevue, WA", company: "求职中 - PD", note: "ACCD本科，UW HCDE硕士，2B/电商/design system设计经验。AI对设计的影响和新的技能，职业发展" },
  ]},
  "Q": { name: "Team Q 立冬", location: "Seattle, WA", region: "Great Seattle Area", members: [
    { en: "Cheche (Chong Guo)", cn: "扯扯", loc: "Seattle, WA", company: "AWS - UX", note: "Georgia Tech Digital Media专业，AWS Agentic AI组。对one-person-startup感兴趣；拓展作为builder的能力；设计领域的Lora和post train" },
    { en: "Huiran Li", cn: "李慧然", loc: "Seattle, WA", company: "Instagram - PD", note: "本科华盛顿大学HCDE，part-time在ArtCenter College of Design上视觉传达设计的课。2021年加入Instagram。想多多体会career growth，了解UX整体行业" },
    { en: "Yuwen Li", cn: "李玉雯", loc: "Seattle, WA", company: "Salesforce - UX", note: "UW HCDE。感兴趣UX design research和职业发展话题" },
    { en: "Yongshang Jiao", cn: "焦永上", loc: "Seattle, WA", company: "Job Searching - PD", note: "HCI/d IUB，Remitly设计师laid off后在找工作。想讨论提高design skills和soft skills。AI时代的机遇和挑战" },
    { en: "Minjun Chen", cn: "", loc: "Seattle, WA", company: "Wrapbook - PD", note: "UW HCID毕业。之前在Wayfair, Amazon Prime, Microsoft Bing, Spotify广告设计组。如何提升产品思维，如何做strategy和design vision" },
    { en: "Ken Pan", cn: "", loc: "Seattle, WA", company: "Ingram Micro - PD", note: "本科THU交互，研究生IIT ID Mdes。比较junior的设计师，好奇怎么在大公司内建立影响力与管理上下关系" },
  ]},
  "R": { name: "Team R 小雪 AI", location: "Seattle, WA / Vancouver, Canada", region: "Great Seattle Area", members: [
    { en: "Siyi Chen", cn: "", loc: "Seattle, WA", company: "Microsoft - PD", note: "Info sci, UX concentrated. Vibecoding/AI时代挑战和机会/大厂生存手册" },
    { en: "Victor Luo", cn: "罗宇阳", loc: "Seattle, WA", company: "Runway - PD", note: "本科USC design，之后在agency Work & Co转做digital product design。目前在Runway做Gen AI方面的设计。AI对设计师工作流以及未来发展的影响" },
    { en: "Constanza Tong", cn: "童画", loc: "Seattle, WA", company: "求职中 - PD", note: "THU BA (HCI track) + CMU MET (ARVR track)。如何用Vibe Coding来empower design decision；AI-powered Product Design；Enterprise UX" },
    { en: "Ruijingya Tang", cn: "", loc: "Seattle, WA", company: "Chartmetric - PD", note: "B2B SaaS; design system。如何在AI时代成长+manage WLB & 心理健康" },
    { en: "Neil Zhu", cn: "朱力涵", loc: "Vancouver, Canada", company: "B-Stock - PD", note: "UMich MSI毕业, 建筑转UX，有过初创公司创始设计师/freelancer经验。什么也都很想要学习" },
  ]},
  "S": { name: "Team S 大雪 AI", location: "New York City, NY", region: "ET (East Coast)", members: [
    { en: "Yunjie Yao", cn: "", loc: "New York City, NY", company: "Futuro AI - ex Dropbox", note: "现在是创始人CEO；UCB - Master in UX; Eng > design。讨论AI在design process的应用；希望招募founding product designer" },
    { en: "Charles Hu", cn: "", loc: "New York City, NY", company: "Meta - PD", note: "浙大工业设计本+密大HCI硕。目前在Meta做commerce相关的设计。AI accelerated design; Design leadership; mentorship; 长期想做产品创新" },
    { en: "Nicole Wang", cn: "", loc: "New York City, NY", company: "ButcherBox - PD", note: "Advertising本+CMU MIIPS硕。职场中如何manage up + AI side projects + 新一轮求职" },
    { en: "Jackie Jiang", cn: "", loc: "New York City, NY", company: "Tennr - PD", note: "经济和艺术双专业背景。在Attentive C轮时期加入，做了strategic design/design manager/product design的工作。最近在转型PM" },
    { en: "Yiwei Lin (Vera)", cn: "", loc: "New York City, NY", company: "CVS - UX", note: "资深设计师，EX-Walmart, CVS。景观建筑转行的UX。AI agent, AI+ecommerce, AI+ads; 设计师职业发展; 求职准备和练习" },
    { en: "Xiao Han", cn: "", loc: "New York City, NY", company: "Meta - PD", note: "PD at Meta. AI趋势下的工作流, AI对职业发展的影响, 认识更多设计师朋友" },
    { en: "Lydia Hong", cn: "", loc: "New York City, NY", company: "Sofamon - PD", note: "本科USC BFA design，之前在Amazon Alexa工作。现在在crypto startup。参与讨论AI对designer的改变，寻求新的工作机会" },
  ]},
  "T": { name: "Team T 冬至 Growth", location: "New York City, NY", region: "ET (East Coast)", members: [
    { en: "Mandy Ding", cn: "", loc: "New York City, NY", company: "ServiceNow - PD", note: "复旦本科，CMU艺术管理硕士。之前在纽约做画廊/拍卖行的艺术市场，2018年转行做UX，一直在做2B design。探讨2B产品的设计经验和动态" },
    { en: "Yifeng Wang", cn: "王奕峰", loc: "New York City, NY", company: "Datadog - PD", note: "建筑设计背景，目前在Datadog做DevSecOps SaaS platform。认识更多设计小伙伴，了解行业趋势，职业发展" },
    { en: "Mengyi Hu", cn: "", loc: "New York City, NY", company: "Postman - PD", note: "从agency做web design开始，然后逐渐转入tech做产品设计。初创Startup到late stage startup做B端产品。工作经验交流和学习" },
    { en: "Danica", cn: "", loc: "New York City, NY", company: "Slalom - UX", note: "本科南大生物医学工程然后研究生转的产品设计。现在在Slalom做UX (咨询公司)。Soft skill提升，在家工作如何和同事connect" },
    { en: "Yue Wang", cn: "", loc: "New York City, NY", company: "Material - UXR", note: "Consulting firm的UXR，工作内容主要是B2B的benchmarking。UX researcher的职业规划，提升产品思维" },
    { en: "Nicole Zhu", cn: "", loc: "New York City, NY", company: "Google - PD", note: "UMich MSI - Google. Drive alignment. Deliver impact" },
  ]},
  "U": { name: "Team U 小寒 Culture", location: "New York City, NY", region: "ET (East Coast)", members: [
    { en: "Kailin Zhu", cn: "猪卡梨", loc: "New York City, NY", company: "Adobe - PD", note: "CUC Anima game eng undergrad, NYU Tisch game design grad. Ex-ustwo, ex-Unity. 0to1, AI creative tooling, XR, game development" },
    { en: "Yiwei Gao", cn: "", loc: "New York City, NY", company: "Meta - PD", note: "Ex建筑师，SaaS产品设计师，曾就职Startup。了解行业动向，职业发展，认识设计师朋友" },
    { en: "Meijie Xia", cn: "夏梅杰", loc: "New York City, NY", company: "Meta - PD", note: "Meta产品设计师, ex-Google, Uber, Chime. Georgia Tech MS-HCI。了解行业动向，知道设计师都在思考什么，职业发展" },
    { en: "Chelsea Chen", cn: "陈晨", loc: "New York City, NY", company: "Candy Digital - PD", note: "NYU ITP毕业，本科是media专业。现在在AI相关行业。想要了解不同行业的UX都有哪些挑战以及行业趋势" },
    { en: "Sue (陈春含)", cn: "陈春含", loc: "New York City, NY", company: "Quora - PD", note: "本科北大，Master NYU-ITP。从22年起开始做Quora的AI产品Poe，主要负责Poe的Core product features。对各种广义的设计都非常有热情" },
    { en: "Kate Xu", cn: "", loc: "New York City, NY", company: "BofA - PD", note: "Cognitive Science, HCI. UX转型UX Engineer面临什么呢？在蹲身份，想找圈里前辈建立mentorship，一起成长" },
  ]},
  "V": { name: "Team V 大寒", location: "Boston / DC / Toronto", region: "ET / Other", members: [
    { en: "Holly Jin", cn: "", loc: "Boston, MA", company: "Gensler - Design Strategy", note: "建筑本科工作几年后目前从事design strategy+consulting。认识其他的设计师，分享职业感悟，了解行业动向" },
    { en: "Weiwei Zhang", cn: "张唯玮", loc: "Boston, MA", company: "HubSpot - PD", note: "目前在HubSpot data platform做设计，之前在Twilio Segment和Wise Systems。计算机+艺术设计+交互设计背景。跨组合作，AI赋能，向上沟通管理" },
    { en: "Jessica Yuan", cn: "", loc: "Washington DC", company: "ScenEQ - PD", note: "本科MICA Graphic Design and Interactive Arts, 研究生UMD HCI。在FINRA做了六年PD，B2B & enterprise products。有两年科技创业经历" },
    { en: "Jasmine Guo", cn: "", loc: "Toronto, Canada", company: "Enable - PD", note: "Senior Product Designer, B2B SaaS。康奈尔info sci本科和研究生。想向其他设计师学习，交流职业发展；Design System best practices" },
  ]},
  "W": { name: "Team W 既白 Growth", location: "Indiana / Miami / NC / Detroit", region: "ET / Other", members: [
    { en: "Yangyi Xu", cn: "", loc: "Indiana", company: "Weights & Biases - PD", note: "本科浙大建筑，研究生GaTech HCI，曾在阿里云实习。Career development; 了解不同industry设计师的process和挑战" },
    { en: "Abby Gao", cn: "高悦", loc: "Miami, FL", company: "Supermove - PD", note: "UC Berkeley建筑+New Media, 毕业后去了design agency，现在在startup做moving industry的SaaS软件。职业发展career growth, 在工作中更多使用AI" },
    { en: "Camilla Zhang", cn: "聪莹", loc: "Research Triangle Park, NC", company: "NetApp - UX", note: "CMU METALS项目毕业后进入NetApp工作5年。B端设计讨论（尤其是存储or云相关），Career path相关" },
    { en: "Xianyou Yang", cn: "", loc: "Detroit, MI", company: "Fujifilm - UX", note: "本科浙大工业设计，研究生RIT HCI。目前在Fujifilm做UX。想学习专业设计师的设计经验和工作发展经验，作品集storytelling的技巧" },
    { en: "Bingyi", cn: "", loc: "Detroit, MI", company: "Eli Lilly - UX", note: "本科MSU Nutritional Science和media的double。研究生UMich HCI。之前在Aptiv做fleet management UX，现在在礼来做AI enterprise tool。面试能力提升, interview techniques" },
  ]},
  "X": { name: "Team X 上巳 Community", location: "Austin / Dallas / Omaha", region: "ET / Other", members: [
    { en: "Janet Dai", cn: "", loc: "Austin, TX", company: "Yahoo - PD", note: "UT Austin研究生毕业，本科工业设计。现在在Yahoo做广告B端产品。工作中如何交流，如何build my name, 如何理解leadership的strategy" },
    { en: "Ce Liang", cn: "梁策", loc: "Austin, TX", company: "Oracle - UX", note: "本科工业设计, 研究生人机交互设计。目前在Oracle的health science部门做UX设计。交流工作中困境和疑惑，了解行业风向" },
    { en: "Jing Lyu (Mila)", cn: "静静", loc: "Dallas, TX", company: "JPMorgan - UXD", note: "本科南京艺术学院，研究生Pratt Institute。2年Clemson University-HCI博士研究生学习。现在摩根大通公司任UX设计师。希望认识更多设计师朋友" },
    { en: "Janie Liu", cn: "", loc: "Omaha, NE", company: "Cisco Meraki - UX", note: "Iowa State研究生HCI, 现在在Cisco Meraki做2B networking design。学习交流，工作分享，career growth" },
  ]},
  "Y": { name: "Team Y 花朝 Community", location: "Tokyo / 深圳 / 台北", region: "Overseas / Other", members: [
    { en: "Lingzhi", cn: "", loc: "Tokyo, Japan", company: "Rakuten - PD", note: "本科北京语言大学数字媒体技术，在CMU MIIPS学习交互设计。之前在VMware做2B产品设计。去年搬到东京在Rakuten做cloud产品设计。交流职场经验和职业发展" },
    { en: "Zirui Cheng", cn: "程子芮", loc: "深圳", company: "Tencent - PD", note: "本科工业设计，研究生HCI，目前在腾讯做广告方面的体验设计。AI, 认识更多设计师朋友" },
    { en: "Ziyan", cn: "", loc: "深圳 / Redwood City, CA", company: "EMW3 - UX", note: "现在新媒体agency做E-commerce产品设计，全球remote。曾有to B初创公司经验。再之前在建筑从业8年。career path的可能性" },
    { en: "Joy W", cn: "", loc: "台北", company: "Former JPMC - PD", note: "本科UCSD Icam Design and minor in CS。之前有两三年UX designer工作经验。目前在找新的工作机会。希望能认识新设计师，了解职场UX的技能走向和市场未来趋势" },
  ]},
};
